package TShirtApp;


/**
* TShirtApp/ColorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tshirt.idl
* Wednesday, April 25, 2018 4:07:27 PM GMT+02:00
*/

abstract public class ColorHelper
{
  private static String  _id = "IDL:TShirtApp/Color:1.0";

  public static void insert (org.omg.CORBA.Any a, TShirtApp.Color that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TShirtApp.Color extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (TShirtApp.ColorHelper.id (), "Color", new String[] { "blue", "red", "black"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TShirtApp.Color read (org.omg.CORBA.portable.InputStream istream)
  {
    return TShirtApp.Color.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TShirtApp.Color value)
  {
    ostream.write_long (value.value ());
  }

}
