package TShirtApp;


/**
* TShirtApp/Color.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tshirt.idl
* Wednesday, April 25, 2018 4:07:27 PM GMT+02:00
*/

public class Color implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static TShirtApp.Color[] __array = new TShirtApp.Color [__size];

  public static final int _blue = 0;
  public static final TShirtApp.Color blue = new TShirtApp.Color(_blue);
  public static final int _red = 1;
  public static final TShirtApp.Color red = new TShirtApp.Color(_red);
  public static final int _black = 2;
  public static final TShirtApp.Color black = new TShirtApp.Color(_black);

  public int value ()
  {
    return __value;
  }

  public static TShirtApp.Color from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Color (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Color
