package TShirtApp;

/**
* TShirtApp/ColorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tshirt.idl
* Wednesday, April 25, 2018 4:07:27 PM GMT+02:00
*/

public final class ColorHolder implements org.omg.CORBA.portable.Streamable
{
  public TShirtApp.Color value = null;

  public ColorHolder ()
  {
  }

  public ColorHolder (TShirtApp.Color initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TShirtApp.ColorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TShirtApp.ColorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TShirtApp.ColorHelper.type ();
  }

}
