package TShirtApp;

/**
* TShirtApp/TshirtHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tshirt.idl
* Wednesday, April 25, 2018 4:07:27 PM GMT+02:00
*/

public final class TshirtHolder implements org.omg.CORBA.portable.Streamable
{
  public TShirtApp.Tshirt value = null;

  public TshirtHolder ()
  {
  }

  public TshirtHolder (TShirtApp.Tshirt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TShirtApp.TshirtHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TShirtApp.TshirtHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TShirtApp.TshirtHelper.type ();
  }

}
