package TShirtApp;


/**
* TShirtApp/TShirtServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tshirt.idl
* Wednesday, April 25, 2018 4:07:27 PM GMT+02:00
*/

public abstract class TShirtServerPOA extends org.omg.PortableServer.Servant
 implements TShirtApp.TShirtServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getPriceOfSimpleTshirt", new java.lang.Integer (0));
    _methods.put ("getPriceOfSpecialTshirt", new java.lang.Integer (1));
    _methods.put ("makeImage", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TShirtApp/TShirtServer/getPriceOfSimpleTshirt
       {
         int width = in.read_long ();
         int height = in.read_long ();
         int $result = (int)0;
         $result = this.getPriceOfSimpleTshirt (width, height);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // TShirtApp/TShirtServer/getPriceOfSpecialTshirt
       {
         TShirtApp.Tshirt TShirt = TShirtApp.TshirtHelper.read (in);
         int $result = (int)0;
         $result = this.getPriceOfSpecialTshirt (TShirt);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // TShirtApp/TShirtServer/makeImage
       {
         String s = in.read_string ();
         byte $result[] = null;
         $result = this.makeImage (s);
         out = $rh.createReply();
         TShirtApp.octetSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TShirtApp/TShirtServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TShirtServer _this() 
  {
    return TShirtServerHelper.narrow(
    super._this_object());
  }

  public TShirtServer _this(org.omg.CORBA.ORB orb) 
  {
    return TShirtServerHelper.narrow(
    super._this_object(orb));
  }


} // class TShirtServerPOA
